apiVersion: v1
kind: Namespace
metadata:
  name: ponnie_world
  labels:
    name: ponnie_world

---
apiVersion: v1
kind: Deployment
metadata:
  name: application1
  namespace: ponnie_world
spec:
  selector:
    matchLabels:
      app: application1
  replicas: 4
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
  template:
    metadata:
      labels:
        app: application1
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: application1
        - maxSkew: 1
          topologyKey: node
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: application1
      containers:
      - name: application1
        image: yeasy/simple-web:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: app-port
          containerPort: 80
          hostPort: 80
        livenessProbe:
          tcpSocket:
            path: /
            port: app-port
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /
            port: app-port
          failureThreshold: 3
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: application1
  namespace: ponnie_world
  labels:
    run: application1
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: application1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application1
  namespace: ponnie_world
spec:
  scaleTargetRef:
    kind: Deployment
    name: application1
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
